# Generated by Django 6.0.5 on 2026-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('subreddit', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('created_utc', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
    ]
